# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: QF Next
email: akhawar@qf.org.qa
description: > # this means to ignore newlines until "baseurl:"
  Jekyll version of QF
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://next.qf.org.qa" # the base hostname & protocol for your site
twitter_username: qf
github_username:  qatarfoundation

# Build settings
markdown: kramdown

# Markdown-specific settings
kramdown:
  auto_ids: true # Auto-generate ID's for headings

# extra gems
# https://github.com/jekyll/jekyll-seo-tag
gems:
  - jekyll-seo-tag

# exclude the ./vendor directory
exclude:
  - vendor

# config elements specific to jeckyll-seo-tag
# https://github.com/jekyll/jekyll-seo-tag
twitter:
  username: qf
logo: https://cdn.qf.com.qa/app/media/42306

# Server Config options
livereload: true    # You no longer need to include --livereload
reload_port: 5678    # If you don't want to use the default port
